In [2]:
import numpy as np
import pandas as pd

In [3]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [4]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [5]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [6]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [7]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [10]:
date['date'] = pd.to_datetime(date['date'])

In [12]:
date['date_year'] = date['date'].dt.year
date['date_month_no'] = date['date'].dt.month
date['date_month_name'] = date['date'].dt.month_name()
date['date_day'] = date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [13]:
date['date_dow'] = date['date'].dt.dayofweek
date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name
0,2019-12-10,2019,12,December,10,1,Tuesday
1,2018-08-15,2018,8,August,15,2,Wednesday
2,2018-10-23,2018,10,October,23,1,Tuesday
3,2019-08-17,2019,8,August,17,5,Saturday
4,2019-01-06,2019,1,January,6,6,Sunday

In [15]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)
date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

In [18]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 6, 15, 13, 29, 4, 755502)

In [19]:
today - date['date']

0     2379 days 13:29:04.755502
1     2861 days 13:29:04.755502
2     2792 days 13:29:04.755502
3     2494 days 13:29:04.755502
4     2717 days 13:29:04.755502
                 ...
995   2807 days 13:29:04.755502
996   2748 days 13:29:04.755502
997   2596 days 13:29:04.755502
998   2661 days 13:29:04.755502
999   2435 days 13:29:04.755502
Name: date, Length: 1000, dtype: timedelta64[ns]

In [20]:
(today - date['date']).dt.days

0      2379
1      2861
2      2792
3      2494
4      2717
       ...
995    2807
996    2748
997    2596
998    2661
999    2435
Name: date, Length: 1000, dtype: int64

In [22]:
np.round((today - date['date'])/ np.timedelta64(1,'m'),0)

0      3426569.0
1      4120649.0
2      4021289.0
3      3592169.0
4      3913289.0
         ...
995    4042889.0
996    3957929.0
997    3739049.0
998    3832649.0
999    3507209.0
Name: date, Length: 1000, dtype: float64

In [23]:
time['date'] = pd.to_datetime(time['date'])

In [24]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

In [25]:
time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [26]:
today - time['date']

0     4565 days 12:39:04.755502
1     4429 days 13:49:04.755502
2     4915 days 13:08:04.755502
3     4217 days 12:58:04.755502
4     4614 days 14:18:04.755502
                 ...
995   5204 days 12:39:04.755502
996   4525 days 14:15:04.755502
997   4990 days 13:52:04.755502
998   5106 days 13:55:04.755502
999   4378 days 14:04:04.755502
Name: date, Length: 1000, dtype: timedelta64[ns]

In [27]:
(today - time['date'])/np.timedelta64(1,'s')

0      3.944615e+08
1      3.827153e+08
2      4.247033e+08
3      3.643955e+08
4      3.987011e+08
           ...
995    4.496711e+08
996    3.910113e+08
997    4.311859e+08
998    4.412085e+08
999    3.783098e+08
Name: date, Length: 1000, dtype: float64

In [28]:
(today - time['date'])/np.timedelta64(1,'m')

0      6.574359e+06
1      6.378589e+06
2      7.078388e+06
3      6.073258e+06
4      6.645018e+06
           ...
995    7.494519e+06
996    6.516855e+06
997    7.186432e+06
998    7.353475e+06
999    6.305164e+06
Name: date, Length: 1000, dtype: float64

In [29]:
(today - time['date'])/np.timedelta64(1,'h')

0      109572.651321
1      106309.817988
2      117973.134654
3      101220.967988
4      110750.301321
           ...
995    124908.651321
996    108614.251321
997    119773.867988
998    122557.917988
999    105086.067988
Name: date, Length: 1000, dtype: float64