In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.read_csv('cars.csv')

In [9]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [10]:
pd.get_dummies(df,columns=['fuel','owner'])

        brand  km_driven  selling_price  ...  owner_Second Owner  owner_Test Drive Car  owner_Third Owner
0      Maruti     145500         450000  ...               False                 False              False
1       Skoda     120000         370000  ...                True                 False              False
2       Honda     140000         158000  ...               False                 False               True
3     Hyundai     127000         225000  ...               False                 False              False
4      Maruti     120000         130000  ...               False                 False              False
...       ...        ...            ...  ...                 ...                   ...                ...
8123  Hyundai     110000         320000  ...               False                 False              False
8124  Hyundai     119000         135000  ...               False                 False              False
8125   Maruti     120000         382000  ...               False                 False              False
8126     Tata      25000         290000  ...               False                 False              False
8127     Tata      25000         290000  ...               False                 False              False

[8128 rows x 12 columns]

In [11]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

        brand  km_driven  selling_price  ...  owner_Second Owner  owner_Test Drive Car  owner_Third Owner
0      Maruti     145500         450000  ...               False                 False              False
1       Skoda     120000         370000  ...                True                 False              False
2       Honda     140000         158000  ...               False                 False               True
3     Hyundai     127000         225000  ...               False                 False              False
4      Maruti     120000         130000  ...               False                 False              False
...       ...        ...            ...  ...                 ...                   ...                ...
8123  Hyundai     110000         320000  ...               False                 False              False
8124  Hyundai     119000         135000  ...               False                 False              False
8125   Maruti     120000         382000  ...               False                 False              False
8126     Tata      25000         290000  ...               False                 False              False
8127     Tata      25000         290000  ...               False                 False              False

[8128 rows x 10 columns]

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test , y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=0)

In [13]:
X_test.head()

         brand  km_driven    fuel        owner
3558   Hyundai      40000  Diesel  First Owner
233   Mahindra      70000  Diesel  First Owner
7952    Maruti       5000  Petrol  First Owner
572     Maruti     120000  Petrol  Third Owner
6960     Lexus      20000  Petrol  First Owner

In [14]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
# ohe = OneHotEncoder(drop='first',sparse_output=False)
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

In [22]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [23]:
X_test_new = ohe.fit_transform(X_test[['fuel','owner']])

In [24]:
X_train_new.shape

(6502, 7)

In [25]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

In [26]:
counts=df['brand'].value_counts()

In [27]:
df['brand'].nunique()
threshold =100

In [28]:
repl = counts[counts <= threshold].index

In [31]:
pd.get_dummies(df['brand'].replace(repl,'uncommon'),dtype=int)

      BMW  Chevrolet  Ford  Honda  Hyundai  Mahindra  Maruti  Renault  Skoda  Tata  Toyota  Volkswagen  uncommon
0       0          0     0      0        0         0       1        0      0     0       0           0         0
1       0          0     0      0        0         0       0        0      1     0       0           0         0
2       0          0     0      1        0         0       0        0      0     0       0           0         0
3       0          0     0      0        1         0       0        0      0     0       0           0         0
4       0          0     0      0        0         0       1        0      0     0       0           0         0
...   ...        ...   ...    ...      ...       ...     ...      ...    ...   ...     ...         ...       ...
8123    0          0     0      0        1         0       0        0      0     0       0           0         0
8124    0          0     0      0        1         0       0        0      0     0       0           0         0
8125    0          0     0      0        0         0       1        0      0     0       0           0         0
8126    0          0     0      0        0         0       0        0      0     1       0           0         0
8127    0          0     0      0        0         0       0        0      0     1       0           0         0

[8128 rows x 13 columns]